MySQL:
  # activate MySQL
  active: false
  # hostname to use to connect to the database, in most cases 'localhost'
  hostname: host
  # username to use to connect to the database
  username: user
  # password to use to connect to the database
  password: pw
  # database name to connect to
  database: db
  # database port to connect to
  port: 3306
  # general statistic table name
  table: pvpstats
  # kill statistic table name
  killtable: pvpkillstats
  # connection options
  options: ?autoReconnect=true
# === [ SQLite Settings ] ===
SQLite:
  # database file name, plugin will append extension '.db'
  filename: database
  # activate SQLite
  active: false
  # general statistic table name
  table: pvpstats
  # kill statistic table name
  killtable: pvpkillstats
# === [ YML Database Emulation Settings ] ===
YML:
  # general statistic file name, plugin will append extension '.yml'
  table: pvpstats
  # # kill statistic file name, plugin will append extension '.yml'
  killtable: pvpkillstats
# === [ Statistic Settings ] ===
statistics:
  # clear (duplicated) statistics on every start
  clearOnStart: true
  # create empty player entry when they join
  createOnJoin: true
  # prevent players from getting kills from the same victim
  checkAbuse: true
  # prevent stats for players without the permission 'pvpstats.nonewbie'
  checkNewbies: true
  # order deaths descending by default (rather than TOP deaths being LESS deaths)
  deathsDescending: false
  # seconds to wait before allowing to kill the same player again to count (-1 will never reset)
  abuseSeconds: -1
  # save every kill - is never read internally, so only for web stats or alike
  collectPrecise: true
  # always reset a streak when a player disconnects
  resetKillstreakOnQuit: false
  # announce lines from streak_announcements.yml on specific streak values
  streakAnnouncements: false
  # issue commands from streak_commands.yml on specific streak values
  streakCommands: false
  # count dying from other sources than players towards death count and resetting of streaks
  countRegularDeaths: false
  # mathematical formula to calculate kill/death ratio
  killDeathCalculation: '&k/(&d+1)'
  # simplify kill/death ratio calculation to just kills per deaths
  killDeathSimple: false
  # time in seconds to consider a former kill an assist
  assistSeconds: 60
# === [ Integration into other Plugins ] ===
other:
  # use players' display names
  displayNames: false
  # count PVP Arena deaths
  PVPArena: false
  OPMessages: true
# world names where not to count statistics
ignoreworlds:
  - doNotTrack
# locations of leaderboards
leaderboards: []
# === [ ELO Score Settings ] ===
eloscore:
  active: false
  # min possible ELO score
  minimum: 18
  # starting ELO score
  default: 1500
  # max possible ELO score
  maximum: 3000
  # K-Factor settings
  k-factor:
    # K-Factor below threshold
    below: 32
    # K-Factor above threshold
    above: 16
    # K-Factor threshold
    threshold: 2000
msg:
  overrides: false
  main:
    - '&cName: &7%n'
    - '&cKills: &7%k'
    - '&cDeaths: &7%d'
    - '&cRatio: &7%r'
    - '&cStreak: &7%s'
    - '&cMax Streak: &7%m'
# === [ Updater Settings ] ===
update:
  # what to do? Valid values: off, announce, download, both
  mode: both
  # which type of branch to get updates? Valid values: dev, alpha, beta, release
  type: beta
# === [ bStats Metrics Settings ] ===
bStats:
  # Should we send stats at all? Please keep this in so we have an overview of spread of versions <3
  enabled: true
  # This setting sends a bit more detailed information about which features are used at all. Thank you for supporting me!
  full: true